name: "mypy"

on:
  workflow_dispatch:
  push:

jobs:
  tagged-release:
    name: "Auto-Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Load in repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Initiate runner
        shell: bash
        run: |
          pip install poetry==1.3.1
          poetry env use 3.10
          poetry install
          poetry run mypy .

      - name: Saving changes to repo
        uses: stefanzweifel/git-auto-commit-action@v4
